"""empty message

Revision ID: 0dbc2980e336
Revises: 3e1225457fac
Create Date: 2021-02-23 05:43:12.452305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dbc2980e336'
down_revision = '3e1225457fac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('creation_Date', sa.DateTime(), nullable=False))
    op.drop_column('Artist', 'start_Date')
    op.add_column('Venue', sa.Column('creation_Date', sa.DateTime(), nullable=False))
    op.drop_column('Venue', 'start_Date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('start_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'creation_Date')
    op.add_column('Artist', sa.Column('start_Date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'creation_Date')
    # ### end Alembic commands ###
