"""empty message

Revision ID: 3e1225457fac
Revises: 431d06df0d2e
Create Date: 2021-02-23 04:28:36.058354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1225457fac'
down_revision = '431d06df0d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('start_Date', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('start_Date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'start_Date')
    op.drop_column('Artist', 'start_Date')
    # ### end Alembic commands ###
