"""empty message

Revision ID: 431d06df0d2e
Revises: b43f35d5e553
Create Date: 2021-02-23 01:25:45.662649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431d06df0d2e'
down_revision = 'b43f35d5e553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talents',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'seeking_talents',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
