"""empty message

Revision ID: 59ef84902e2f
Revises: d4b3d54c8afa
Create Date: 2021-02-22 17:01:47.788542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ef84902e2f'
down_revision = 'd4b3d54c8afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_shows', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'seeking_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_show', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'seeking_shows')
    # ### end Alembic commands ###
