"""empty message

Revision ID: b43f35d5e553
Revises: 5733119823d4
Create Date: 2021-02-23 01:23:49.645135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43f35d5e553'
down_revision = '5733119823d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talents', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talents')
    # ### end Alembic commands ###
