"""empty message

Revision ID: d4b3d54c8afa
Revises: 9bf892db8edd
Create Date: 2021-02-22 16:59:45.745437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b3d54c8afa'
down_revision = '9bf892db8edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_show', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_show')
    # ### end Alembic commands ###
